#!/usr/bin/env bash
set -u

# Read-only field data collector for SpiritWing/Lukong UAV integration.
# It does not publish commands, arm, take off, land, or change flight modes.

SCRIPT_NAME="$(basename "$0")"
STAMP="$(date +%Y%m%d_%H%M%S)"
OUT_DIR="${1:-$HOME/spiritwing_info_$STAMP}"

mkdir -p "$OUT_DIR"

log() {
  echo "[$(date '+%F %T')] $*" | tee -a "$OUT_DIR/collect.log"
}

run_cmd() {
  local name="$1"
  shift
  local file="$OUT_DIR/$name.txt"
  log "RUN $name: $*"
  {
    echo "# $name"
    echo "# command: $*"
    echo "# time: $(date '+%F %T')"
    echo
    "$@"
  } >"$file" 2>&1
  local rc=$?
  echo "# exit_code: $rc" >>"$file"
  return 0
}

run_timeout() {
  local seconds="$1"
  local name="$2"
  shift 2
  if command -v timeout >/dev/null 2>&1; then
    run_cmd "$name" timeout "$seconds" "$@"
  else
    run_cmd "$name" "$@"
  fi
}

topic_type() {
  local topic="$1"
  rostopic type "$topic" 2>/dev/null | head -n 1
}

collect_topic() {
  local label="$1"
  local topic="$2"
  log "Collect topic $label: $topic"
  run_timeout 3 "topic_type_${label}" rostopic type "$topic"
  run_timeout 3 "topic_info_${label}" rostopic info "$topic"
  run_timeout 8 "topic_echo_once_${label}" rostopic echo -n 1 "$topic"
  run_timeout 8 "topic_hz_${label}" rostopic hz "$topic"
}

collect_service() {
  local label="$1"
  local service="$2"
  log "Collect service $label: $service"
  run_timeout 3 "service_type_${label}" rosservice type "$service"
  run_timeout 3 "service_info_${label}" rosservice info "$service"
}

log "$SCRIPT_NAME starting"
log "Output directory: $OUT_DIR"

cat >"$OUT_DIR/README.txt" <<EOF
SpiritWing/Lukong UAV information collection result.

This directory was generated by:
  $SCRIPT_NAME

The script is read-only. It collects ROS environment, topic list, message
definitions, selected topic samples, MAVROS state, TF, and possible map files.

Please send the whole directory back to the developer.
EOF

run_cmd "system_uname" uname -a
run_cmd "system_date" date
run_cmd "env_ros" env
run_cmd "rosversion_ros" rosversion -d
run_cmd "roswtf" roswtf

run_timeout 5 "rosnode_list" rosnode list
run_timeout 5 "rostopic_list" rostopic list
run_timeout 5 "rosservice_list" rosservice list
run_timeout 5 "rosparam_list" rosparam list
run_timeout 5 "rosparam_dump" rosparam dump "$OUT_DIR/rosparams.yaml"
run_timeout 10 "rostopic_type_table" bash -lc 'for t in $(rostopic list 2>/dev/null); do printf "%s " "$t"; rostopic type "$t" 2>/dev/null || true; done'
run_timeout 10 "rosservice_type_table" bash -lc 'for s in $(rosservice list 2>/dev/null); do printf "%s " "$s"; rosservice type "$s" 2>/dev/null || true; done'

for msg in \
  swing_msgs/UAVCommand \
  swing_msgs/PatrolState \
  swing_msgs/UIState \
  swing_msgs/SensorState \
  swing_msgs/State \
  swing_msgs/ControlState \
  swing_msgs/Setup \
  swing_msgs/TextInfo \
  mavros_msgs/State \
  mavros_msgs/ExtendedState \
  sensor_msgs/BatteryState \
  sensor_msgs/Range \
  sensor_msgs/NavSatFix \
  nav_msgs/Odometry \
  nav_msgs/Path \
  nav_msgs/OccupancyGrid \
  geometry_msgs/PoseStamped \
  geometry_msgs/Twist \
  mavros_msgs/ActuatorControl \
  sensor_msgs/PointCloud2
do
  safe="${msg//\//_}"
  run_timeout 5 "rosmsg_show_${safe}" rosmsg show "$msg"
done

for srv in \
  mavros_msgs/CommandBool \
  mavros_msgs/SetMode \
  mavros_msgs/CommandTOL
do
  safe="${srv//\//_}"
  run_timeout 5 "rossrv_show_${safe}" rossrv show "$srv"
done

collect_topic "mavros_state" "/mavros/state"
collect_topic "mavros_extended_state" "/mavros/extended_state"
collect_topic "mavros_battery" "/mavros/battery"
collect_topic "mavros_local_pose" "/mavros/local_position/pose"
collect_topic "mavros_local_velocity" "/mavros/local_position/velocity_local"
collect_topic "mavros_body_velocity" "/mavros/local_position/velocity_body"
collect_topic "mavros_imu" "/mavros/imu/data"
collect_topic "mavros_global_position" "/mavros/global_position/global"
collect_topic "mavros_home_position" "/mavros/home_position/home"
collect_topic "mavros_rc_in" "/mavros/rc/in"
collect_topic "mavros_manual_control" "/mavros/manual_control/control"
collect_topic "odom_uppercase" "/Odometry"
collect_topic "odometry" "/Odometry"
collect_topic "odom_spiritwing_typo" "/spiritwing/oodm"
collect_topic "odom_spiritwing" "/spiritwing/odom"
collect_topic "mavros_local_odom" "/mavros/local_position/odom"
collect_topic "spiritwing_state" "/spiritwing/state"
collect_topic "spiritwing_sensor_state" "/spiritwing/sensor_state"
collect_topic "spiritwing_control_state" "/spiritwing/control_state"
collect_topic "spiritwing_ui_state" "/spiritwing/ui_state"
collect_topic "spiritwing_setup" "/spiritwing/setup"
collect_topic "spiritwing_text_info" "/spiritwing/text_info"
collect_topic "spiritwing_offset_pose" "/spiritwing/offset_pose"
collect_topic "spiritwing_trajectory" "/spiritwing/trajectory"
collect_topic "spiritwing_patrol_goal" "/spiritwing/patrol_goal"
collect_topic "spiritwing_want_local_plan" "/spiritwing/want_local_plan"
collect_topic "spiritwing_uav_mesh" "/spiritwing/uav_mesh"
collect_topic "patrol_state" "/spiritwing/patrol_state"
collect_topic "patrol_points" "/spiritwing/patrol_points"
collect_topic "move_base_simple_goal" "/move_base_simple/goal"
collect_topic "cmd_vel" "/cmd_vel"
collect_topic "mavros_actuator_control" "/mavros/actuator_control"
collect_topic "command" "/spiritwing/command"
collect_topic "livox_lidar" "/livox/lidar"
collect_topic "livox_cloud_world" "/livox/cloud_in_world"
collect_topic "laser_map" "/Laser_map"
collect_topic "laser_map" "/Laser_map"
collect_topic "laser_map_filter" "/Laser_map_filter"
collect_topic "cloud_registered" "/cloud_registered"
collect_topic "cloud_registered" "/cloud_registered"
collect_topic "cloud_registered_body" "/cloud_registered_body"
collect_topic "filtered_points_ground" "/filtered_points_ground"
collect_topic "filtered_points_no_ground" "/filtered_points_no_ground"
collect_topic "fast_lio_map_global" "/fast_lio_sam/mapping/map_global_optimized"
collect_topic "occu_raw_map" "/occu_raw_map"
collect_topic "occu_inflate_map" "/occu_inflate_map"
collect_topic "planner_goal_point" "/swing_planner_node/goal_point"
collect_topic "planner_occupancy" "/swing_planner_node/grid_map/occupancy"
collect_topic "planning_trajectory" "/planning/trajectory"
collect_topic "mavros_mission_reached" "/mavros/mission/reached"
collect_topic "tof_range" "/tof/range"
collect_topic "map" "/map"
collect_topic "map_metadata" "/map_metadata"
collect_topic "tf" "/tf"
collect_topic "tf_static" "/tf_static"
collect_topic "camera_image_raw" "/camera/image_raw"
collect_topic "usb_cam_image_raw" "/usb_cam/image_raw"
collect_topic "image_raw" "/image_raw"
collect_topic "mavros_camera_image_captured" "/mavros/camera/image_captured"

collect_service "mavros_arming" "/mavros/cmd/arming"
collect_service "mavros_set_mode" "/mavros/set_mode"
collect_service "mavros_takeoff" "/mavros/cmd/takeoff"
collect_service "mavros_land" "/mavros/cmd/land"
collect_service "save_map" "/save_map"
collect_service "dynamic_map" "/dynamic_map"
collect_service "static_map" "/static_map"
collect_service "pub_map" "/pub_map"
collect_service "send_map_srv" "/send_map_srv"
collect_service "save_pose" "/save_pose"
collect_service "mavros_command" "/mavros/cmd/command"
collect_service "mavros_set_home" "/mavros/cmd/set_home"
collect_service "mavros_mission_pull" "/mavros/mission/pull"
collect_service "mavros_mission_push" "/mavros/mission/push"
collect_service "mavros_mission_clear" "/mavros/mission/clear"

run_timeout 5 "topics_spiritwing" bash -lc "rostopic list | grep -Ei 'spirit|swing|patrol|uav|drone|odom|lio|livox|lidar|map|mavros|move_base|cmd_vel|cloud' || true"
run_timeout 5 "services_spiritwing" bash -lc "rosservice list | grep -Ei 'spirit|swing|patrol|uav|drone|map|mavros|move_base' || true"
run_timeout 5 "packages_swing" bash -lc "rospack list | grep -Ei 'swing|spirit|uav|fast|lio|livox|mavros|manager|car|teb|dynamic|pcl' || true"
run_timeout 10 "package_paths" bash -lc "for p in swing_msgs spiritwing_web mavros fast_lio fast_lio2 fast_lio_sam livox_ros_driver livox_ros_driver2 manager_gui car_bringup teb_local_planner_tutorials dynamic_mapping pcl_test vision_to_mavros uav_control; do printf '%s ' \"\$p\"; rospack find \"\$p\" 2>/dev/null || true; done"
run_timeout 10 "workspace_files" bash -lc "ls -lah \$HOME 2>/dev/null; for d in \$HOME/spritwing_v1.0 \$HOME/spirit-wing_v1.0 \$HOME/HZBZ \$HOME/ifc_plus \$HOME/spiritwing_web; do echo; echo '===== '\"\$d\"' ====='; ls -lah \"\$d\" 2>/dev/null || true; find \"\$d\" -maxdepth 4 -type f \\( -name 'step*.sh' -o -name 'start*.sh' -o -name '*.launch' -o -name '*.yaml' -o -name '*.msg' -o -name '*.srv' -o -name '*.py' \\) 2>/dev/null | sort | head -n 500; done"
run_timeout 10 "startup_scripts_content" bash -lc "for d in \$HOME/spritwing_v1.0 \$HOME/spirit-wing_v1.0 \$HOME/HZBZ \$HOME/ifc_plus; do for f in \$(find \"\$d\" -maxdepth 5 -type f \\( -name 'step*.sh' -o -name 'start*.sh' -o -name 'cmd_mavros.py' \\) 2>/dev/null | sort); do echo '===== '\"\$f\"' ====='; sed -n '1,240p' \"\$f\"; echo; done; done"
run_timeout 10 "custom_msg_srv_files" bash -lc "for d in \$(rospack list 2>/dev/null | awk '/swing|spirit|uav|patrol|planner|ground_control|manager|dynamic|pcl|teb|car_bringup|livox|lio/ {print \$2}'); do echo '===== package dir: '\"\$d\"' ====='; find \"\$d\" -maxdepth 4 -type f \\( -name '*.msg' -o -name '*.srv' -o -name '*.action' \\) 2>/dev/null | sort; done"

if command -v rosrun >/dev/null 2>&1; then
  run_timeout 10 "tf_frames" rosrun tf view_frames
  if [ -f frames.pdf ]; then
    mv frames.pdf "$OUT_DIR/frames.pdf"
  fi
fi

run_timeout 10 "tf_echo_world_base_link" rosrun tf tf_echo world base_link
run_timeout 10 "tf_echo_map_base_link" rosrun tf tf_echo map base_link
run_timeout 10 "tf_echo_odom_base_link" rosrun tf tf_echo odom base_link
run_timeout 10 "tf_echo_world_lidar" rosrun tf tf_echo world lidar_link
run_timeout 10 "tf_echo_base_lidar" rosrun tf tf_echo base_link lidar_link

run_timeout 10 "possible_map_files_home" bash -lc "find \$HOME -maxdepth 5 -type f \\( -name '*.pgm' -o -name '*.yaml' -o -name '*.pcd' -o -name 'pose.txt' -o -name 'point_record.txt' \\) 2>/dev/null | sort | head -n 300"
run_timeout 10 "possible_map_files_tmp" bash -lc "find /tmp -maxdepth 4 -type f \\( -name '*.pgm' -o -name '*.yaml' -o -name '*.pcd' -o -name 'pose.txt' -o -name 'point_record.txt' \\) 2>/dev/null | sort | head -n 300"
run_timeout 10 "video_devices" bash -lc "ls -lah /dev/video* 2>/dev/null || true; echo; for d in /dev/video*; do [ -e \"\$d\" ] || continue; echo '===== '\"\$d\"' ====='; v4l2-ctl -d \"\$d\" --all 2>/dev/null || true; v4l2-ctl -d \"\$d\" --list-formats-ext 2>/dev/null || true; done"
run_timeout 10 "video_topics" bash -lc "rostopic list | grep -Ei 'image|camera|video|compressed|usb_cam|gscam|rtsp|stream' || true"
run_timeout 10 "video_processes" bash -lc "ps -eo pid,ppid,stat,cmd | grep -Ei 'ffmpeg|gst|gstreamer|camera|video|rtsp|usb_cam|gscam|opencv|mediamtx|yolo|detect' | grep -v grep || true"
run_timeout 10 "detect_video_files" bash -lc "if [ -d \$HOME/detect ]; then echo '===== ~/detect ====='; ls -lah \$HOME/detect; echo; find \$HOME/detect -maxdepth 2 -type f \\( -name '*.yml' -o -name '*.yaml' -o -name '*.py' -o -name '*.sh' \\) 2>/dev/null | sort; fi"
run_timeout 10 "detect_video_config_content" bash -lc "for f in \$HOME/detect/start.sh \$HOME/detect/rtsp2rtsp.py \$HOME/detect/mediamtx.yml \$HOME/detect/mediamtx.yaml; do [ -f \"\$f\" ] || continue; echo '===== '\"\$f\"' ====='; sed -n '1,240p' \"\$f\"; echo; done"
run_timeout 10 "running_processes" bash -lc "ps -eo pid,ppid,stat,cmd | grep -Ei 'ros|mavros|spirit|swing|livox|lio|px4|mavlink|ffmpeg|gst|camera|video|rtsp' | grep -v grep || true"

cat >"$OUT_DIR/summary_checklist.txt" <<EOF
Please check these files first:

1. rosmsg_show_swing_msgs_UAVCommand.txt
   - Needed to implement /spiritwing/command.

2. rosmsg_show_swing_msgs_PatrolState.txt
   - Needed to parse navigation feedback.

3. topic_type_odom_uppercase.txt / topic_echo_once_odom_uppercase.txt
   - Confirms whether /Odometry is the correct pose topic.

4. topic_type_odom_spiritwing_typo.txt and topic_type_odom_spiritwing.txt
   - Confirms whether the document typo /spiritwing/oodm is real.

5. topic_echo_once_patrol_state.txt
   - Needed to map arrived/finished/failed state.

6. topic_echo_once_livox_lidar.txt and topic_hz_livox_lidar.txt
   - Needed for realtime point cloud upload.

7. possible_map_files_home.txt
   - Needed to locate map.pgm/map.yaml output from mapping scripts.

8. startup_scripts_content.txt and workspace_files.txt
   - Needed to confirm step0_sensor.sh, step1_getMap.sh, step2_mission.sh.

9. rostopic_type_table.txt and rosservice_type_table.txt
   - Needed to discover undocumented topics/services.
EOF

log "Done. Please send this directory: $OUT_DIR"
echo
echo "Collection finished."
echo "Output directory: $OUT_DIR"
