// Generated by gencpp from file epgeneral_task_control/TaskExecutionFeedback.msg
// DO NOT EDIT!


#ifndef EPGENERAL_TASK_CONTROL_MESSAGE_TASKEXECUTIONFEEDBACK_H
#define EPGENERAL_TASK_CONTROL_MESSAGE_TASKEXECUTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace epgeneral_task_control
{
template <class ContainerAllocator>
struct TaskExecutionFeedback_
{
  typedef TaskExecutionFeedback_<ContainerAllocator> Type;

  TaskExecutionFeedback_()
    : request_id()
    , task_id()
    , subtask_id()
    , device_id()
    , execution_id()
    , revision(0)
    , state()
    , waypoint_index(0)
    , waypoint_count(0)
    , progress(0.0)
    , position()
    , error_code()
    , message()  {
    }
  TaskExecutionFeedback_(const ContainerAllocator& _alloc)
    : request_id(_alloc)
    , task_id(_alloc)
    , subtask_id(_alloc)
    , device_id(_alloc)
    , execution_id(_alloc)
    , revision(0)
    , state(_alloc)
    , waypoint_index(0)
    , waypoint_count(0)
    , progress(0.0)
    , position(_alloc)
    , error_code(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_id_type;
  _request_id_type request_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subtask_id_type;
  _subtask_id_type subtask_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _device_id_type;
  _device_id_type device_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _execution_id_type;
  _execution_id_type execution_id;

   typedef uint32_t _revision_type;
  _revision_type revision;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef int32_t _waypoint_index_type;
  _waypoint_index_type waypoint_index;

   typedef int32_t _waypoint_count_type;
  _waypoint_count_type waypoint_count;

   typedef double _progress_type;
  _progress_type progress;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TaskExecutionFeedback_

typedef ::epgeneral_task_control::TaskExecutionFeedback_<std::allocator<void> > TaskExecutionFeedback;

typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionFeedback > TaskExecutionFeedbackPtr;
typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionFeedback const> TaskExecutionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator1> & lhs, const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.request_id == rhs.request_id &&
    lhs.task_id == rhs.task_id &&
    lhs.subtask_id == rhs.subtask_id &&
    lhs.device_id == rhs.device_id &&
    lhs.execution_id == rhs.execution_id &&
    lhs.revision == rhs.revision &&
    lhs.state == rhs.state &&
    lhs.waypoint_index == rhs.waypoint_index &&
    lhs.waypoint_count == rhs.waypoint_count &&
    lhs.progress == rhs.progress &&
    lhs.position == rhs.position &&
    lhs.error_code == rhs.error_code &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator1> & lhs, const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace epgeneral_task_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992f61c604e3ed23f3589fd880757815";
  }

  static const char* value(const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992f61c604e3ed23ULL;
  static const uint64_t static_value2 = 0xf3589fd880757815ULL;
};

template<class ContainerAllocator>
struct DataType< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epgeneral_task_control/TaskExecutionFeedback";
  }

  static const char* value(const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_id\n"
"string task_id\n"
"string subtask_id\n"
"string device_id\n"
"string execution_id\n"
"uint32 revision\n"
"string state\n"
"int32 waypoint_index\n"
"int32 waypoint_count\n"
"float64 progress\n"
"geometry_msgs/Point position\n"
"string error_code\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_id);
      stream.next(m.task_id);
      stream.next(m.subtask_id);
      stream.next(m.device_id);
      stream.next(m.execution_id);
      stream.next(m.revision);
      stream.next(m.state);
      stream.next(m.waypoint_index);
      stream.next(m.waypoint_count);
      stream.next(m.progress);
      stream.next(m.position);
      stream.next(m.error_code);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskExecutionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epgeneral_task_control::TaskExecutionFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "request_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "subtask_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subtask_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "execution_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.execution_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "revision: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoint_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoint_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoint_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoint_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "progress: ";
    Printer<double>::stream(s, indent + "  ", v.progress);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPGENERAL_TASK_CONTROL_MESSAGE_TASKEXECUTIONFEEDBACK_H
