// Generated by gencpp from file epgeneral_task_control/TaskExecutionCommand.msg
// DO NOT EDIT!


#ifndef EPGENERAL_TASK_CONTROL_MESSAGE_TASKEXECUTIONCOMMAND_H
#define EPGENERAL_TASK_CONTROL_MESSAGE_TASKEXECUTIONCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epgeneral_task_control
{
template <class ContainerAllocator>
struct TaskExecutionCommand_
{
  typedef TaskExecutionCommand_<ContainerAllocator> Type;

  TaskExecutionCommand_()
    : action(0)
    , request_id()
    , task_id()
    , subtask_id()
    , device_id()
    , execution_id()
    , revision(0)
    , xml_path()
    , frame_id()
    , map_id()
    , scheduled_at()  {
    }
  TaskExecutionCommand_(const ContainerAllocator& _alloc)
    : action(0)
    , request_id(_alloc)
    , task_id(_alloc)
    , subtask_id(_alloc)
    , device_id(_alloc)
    , execution_id(_alloc)
    , revision(0)
    , xml_path(_alloc)
    , frame_id(_alloc)
    , map_id(_alloc)
    , scheduled_at()  {
  (void)_alloc;
    }



   typedef uint8_t _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_id_type;
  _request_id_type request_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subtask_id_type;
  _subtask_id_type subtask_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _device_id_type;
  _device_id_type device_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _execution_id_type;
  _execution_id_type execution_id;

   typedef uint32_t _revision_type;
  _revision_type revision;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _xml_path_type;
  _xml_path_type xml_path;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_id_type;
  _map_id_type map_id;

   typedef ros::Time _scheduled_at_type;
  _scheduled_at_type scheduled_at;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SCHEDULE)
  #undef SCHEDULE
#endif
#if defined(_WIN32) && defined(CANCEL)
  #undef CANCEL
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(PREPARE)
  #undef PREPARE
#endif
#if defined(_WIN32) && defined(UNLOAD)
  #undef UNLOAD
#endif

  enum {
    SCHEDULE = 1u,
    CANCEL = 2u,
    STOP = 3u,
    PREPARE = 4u,
    UNLOAD = 5u,
  };


  typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TaskExecutionCommand_

typedef ::epgeneral_task_control::TaskExecutionCommand_<std::allocator<void> > TaskExecutionCommand;

typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionCommand > TaskExecutionCommandPtr;
typedef boost::shared_ptr< ::epgeneral_task_control::TaskExecutionCommand const> TaskExecutionCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator1> & lhs, const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.request_id == rhs.request_id &&
    lhs.task_id == rhs.task_id &&
    lhs.subtask_id == rhs.subtask_id &&
    lhs.device_id == rhs.device_id &&
    lhs.execution_id == rhs.execution_id &&
    lhs.revision == rhs.revision &&
    lhs.xml_path == rhs.xml_path &&
    lhs.frame_id == rhs.frame_id &&
    lhs.map_id == rhs.map_id &&
    lhs.scheduled_at == rhs.scheduled_at;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator1> & lhs, const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace epgeneral_task_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b02f521e09d483449a5b659a3a48f813";
  }

  static const char* value(const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb02f521e09d48344ULL;
  static const uint64_t static_value2 = 0x9a5b659a3a48f813ULL;
};

template<class ContainerAllocator>
struct DataType< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epgeneral_task_control/TaskExecutionCommand";
  }

  static const char* value(const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 SCHEDULE=1\n"
"uint8 CANCEL=2\n"
"uint8 STOP=3\n"
"uint8 PREPARE=4\n"
"uint8 UNLOAD=5\n"
"uint8 action\n"
"string request_id\n"
"string task_id\n"
"string subtask_id\n"
"string device_id\n"
"string execution_id\n"
"uint32 revision\n"
"string xml_path\n"
"string frame_id\n"
"string map_id\n"
"time scheduled_at\n"
;
  }

  static const char* value(const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.request_id);
      stream.next(m.task_id);
      stream.next(m.subtask_id);
      stream.next(m.device_id);
      stream.next(m.execution_id);
      stream.next(m.revision);
      stream.next(m.xml_path);
      stream.next(m.frame_id);
      stream.next(m.map_id);
      stream.next(m.scheduled_at);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskExecutionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epgeneral_task_control::TaskExecutionCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "request_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "subtask_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subtask_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "device_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.device_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "execution_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.execution_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "revision: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xml_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.xml_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "scheduled_at: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.scheduled_at);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPGENERAL_TASK_CONTROL_MESSAGE_TASKEXECUTIONCOMMAND_H
