// Generated by gencpp from file ground_air_msgs/LoadMapRequest.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_LOADMAPREQUEST_H
#define GROUND_AIR_MSGS_MESSAGE_LOADMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ground_air_msgs
{
template <class ContainerAllocator>
struct LoadMapRequest_
{
  typedef LoadMapRequest_<ContainerAllocator> Type;

  LoadMapRequest_()
    : map_id()
    , source_uri()  {
    }
  LoadMapRequest_(const ContainerAllocator& _alloc)
    : map_id(_alloc)
    , source_uri(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_id_type;
  _map_id_type map_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_uri_type;
  _source_uri_type source_uri;





  typedef boost::shared_ptr< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadMapRequest_

typedef ::ground_air_msgs::LoadMapRequest_<std::allocator<void> > LoadMapRequest;

typedef boost::shared_ptr< ::ground_air_msgs::LoadMapRequest > LoadMapRequestPtr;
typedef boost::shared_ptr< ::ground_air_msgs::LoadMapRequest const> LoadMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_id == rhs.map_id &&
    lhs.source_uri == rhs.source_uri;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d03ea8f44443b8e20617fdf8c7bf1d5";
  }

  static const char* value(const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d03ea8f44443b8eULL;
  static const uint64_t static_value2 = 0x20617fdf8c7bf1d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/LoadMapRequest";
  }

  static const char* value(const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_id\n"
"string source_uri\n"
;
  }

  static const char* value(const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_id);
      stream.next(m.source_uri);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::LoadMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::LoadMapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "map_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_uri: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_uri);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_LOADMAPREQUEST_H
