// Generated by gencpp from file ground_air_msgs/LoadMap.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_LOADMAP_H
#define GROUND_AIR_MSGS_MESSAGE_LOADMAP_H

#include <ros/service_traits.h>


#include <ground_air_msgs/LoadMapRequest.h>
#include <ground_air_msgs/LoadMapResponse.h>


namespace ground_air_msgs
{

struct LoadMap
{

typedef LoadMapRequest Request;
typedef LoadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadMap
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::LoadMap > {
  static const char* value()
  {
    return "0ad4fcd56eceaa84d4b9013dcb5a122f";
  }

  static const char* value(const ::ground_air_msgs::LoadMap&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::LoadMap > {
  static const char* value()
  {
    return "ground_air_msgs/LoadMap";
  }

  static const char* value(const ::ground_air_msgs::LoadMap&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::LoadMapRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::LoadMap >
template<>
struct MD5Sum< ::ground_air_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::LoadMap >::value();
  }
  static const char* value(const ::ground_air_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::LoadMapRequest> should match
// service_traits::DataType< ::ground_air_msgs::LoadMap >
template<>
struct DataType< ::ground_air_msgs::LoadMapRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::LoadMap >::value();
  }
  static const char* value(const ::ground_air_msgs::LoadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::LoadMapResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::LoadMap >
template<>
struct MD5Sum< ::ground_air_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::LoadMap >::value();
  }
  static const char* value(const ::ground_air_msgs::LoadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::LoadMapResponse> should match
// service_traits::DataType< ::ground_air_msgs::LoadMap >
template<>
struct DataType< ::ground_air_msgs::LoadMapResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::LoadMap >::value();
  }
  static const char* value(const ::ground_air_msgs::LoadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_LOADMAP_H
