// Generated by gencpp from file ground_air_msgs/MappingStatus.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_MAPPINGSTATUS_H
#define GROUND_AIR_MSGS_MESSAGE_MAPPINGSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct MappingStatus_
{
  typedef MappingStatus_<ContainerAllocator> Type;

  MappingStatus_()
    : header()
    , state(0)
    , map_id()
    , point_count(0)
    , map_area(0.0)
    , message()  {
    }
  MappingStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , map_id(_alloc)
    , point_count(0)
    , map_area(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_id_type;
  _map_id_type map_id;

   typedef uint64_t _point_count_type;
  _point_count_type point_count;

   typedef double _map_area_type;
  _map_area_type map_area;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IDLE)
  #undef IDLE
#endif
#if defined(_WIN32) && defined(RECORDING)
  #undef RECORDING
#endif
#if defined(_WIN32) && defined(SAVING)
  #undef SAVING
#endif
#if defined(_WIN32) && defined(COMPLETE)
  #undef COMPLETE
#endif
#if defined(_WIN32) && defined(ERROR)
  #undef ERROR
#endif

  enum {
    IDLE = 0u,
    RECORDING = 1u,
    SAVING = 2u,
    COMPLETE = 3u,
    ERROR = 4u,
  };


  typedef boost::shared_ptr< ::ground_air_msgs::MappingStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::MappingStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MappingStatus_

typedef ::ground_air_msgs::MappingStatus_<std::allocator<void> > MappingStatus;

typedef boost::shared_ptr< ::ground_air_msgs::MappingStatus > MappingStatusPtr;
typedef boost::shared_ptr< ::ground_air_msgs::MappingStatus const> MappingStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::MappingStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::MappingStatus_<ContainerAllocator1> & lhs, const ::ground_air_msgs::MappingStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.map_id == rhs.map_id &&
    lhs.point_count == rhs.point_count &&
    lhs.map_area == rhs.map_area &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::MappingStatus_<ContainerAllocator1> & lhs, const ::ground_air_msgs::MappingStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::MappingStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::MappingStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::MappingStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7b4d3ace6c9bf72b66602ccfc54bf23";
  }

  static const char* value(const ::ground_air_msgs::MappingStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7b4d3ace6c9bf72ULL;
  static const uint64_t static_value2 = 0xb66602ccfc54bf23ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/MappingStatus";
  }

  static const char* value(const ::ground_air_msgs::MappingStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 IDLE=0\n"
"uint8 RECORDING=1\n"
"uint8 SAVING=2\n"
"uint8 COMPLETE=3\n"
"uint8 ERROR=4\n"
"\n"
"uint8 state\n"
"string map_id\n"
"uint64 point_count\n"
"float64 map_area\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ground_air_msgs::MappingStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.map_id);
      stream.next(m.point_count);
      stream.next(m.map_area);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MappingStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::MappingStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point_count: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.point_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_area: ";
    Printer<double>::stream(s, indent + "  ", v.map_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_MAPPINGSTATUS_H
