// Generated by gencpp from file ground_air_msgs/MissionStatus.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_MISSIONSTATUS_H
#define GROUND_AIR_MSGS_MESSAGE_MISSIONSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct MissionStatus_
{
  typedef MissionStatus_<ContainerAllocator> Type;

  MissionStatus_()
    : header()
    , state(0)
    , current_index(0)
    , total_goals(0)
    , mission_id()
    , detail()  {
    }
  MissionStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)
    , current_index(0)
    , total_goals(0)
    , mission_id(_alloc)
    , detail(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint32_t _current_index_type;
  _current_index_type current_index;

   typedef uint32_t _total_goals_type;
  _total_goals_type total_goals;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mission_id_type;
  _mission_id_type mission_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detail_type;
  _detail_type detail;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IDLE)
  #undef IDLE
#endif
#if defined(_WIN32) && defined(RUNNING)
  #undef RUNNING
#endif
#if defined(_WIN32) && defined(DWELLING)
  #undef DWELLING
#endif
#if defined(_WIN32) && defined(PAUSED)
  #undef PAUSED
#endif
#if defined(_WIN32) && defined(SUCCEEDED)
  #undef SUCCEEDED
#endif
#if defined(_WIN32) && defined(FAILED)
  #undef FAILED
#endif
#if defined(_WIN32) && defined(CANCELED)
  #undef CANCELED
#endif
#if defined(_WIN32) && defined(WAITING_FOR_LAND)
  #undef WAITING_FOR_LAND
#endif

  enum {
    IDLE = 0u,
    RUNNING = 1u,
    DWELLING = 2u,
    PAUSED = 3u,
    SUCCEEDED = 4u,
    FAILED = 5u,
    CANCELED = 6u,
    WAITING_FOR_LAND = 7u,
  };


  typedef boost::shared_ptr< ::ground_air_msgs::MissionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::MissionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MissionStatus_

typedef ::ground_air_msgs::MissionStatus_<std::allocator<void> > MissionStatus;

typedef boost::shared_ptr< ::ground_air_msgs::MissionStatus > MissionStatusPtr;
typedef boost::shared_ptr< ::ground_air_msgs::MissionStatus const> MissionStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::MissionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::MissionStatus_<ContainerAllocator1> & lhs, const ::ground_air_msgs::MissionStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state == rhs.state &&
    lhs.current_index == rhs.current_index &&
    lhs.total_goals == rhs.total_goals &&
    lhs.mission_id == rhs.mission_id &&
    lhs.detail == rhs.detail;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::MissionStatus_<ContainerAllocator1> & lhs, const ::ground_air_msgs::MissionStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::MissionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::MissionStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::MissionStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23946ede182678d2d602626aab96cd05";
  }

  static const char* value(const ::ground_air_msgs::MissionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23946ede182678d2ULL;
  static const uint64_t static_value2 = 0xd602626aab96cd05ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/MissionStatus";
  }

  static const char* value(const ::ground_air_msgs::MissionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 IDLE=0\n"
"uint8 RUNNING=1\n"
"uint8 DWELLING=2\n"
"uint8 PAUSED=3\n"
"uint8 SUCCEEDED=4\n"
"uint8 FAILED=5\n"
"uint8 CANCELED=6\n"
"uint8 WAITING_FOR_LAND=7\n"
"\n"
"uint8 state\n"
"uint32 current_index\n"
"uint32 total_goals\n"
"string mission_id\n"
"string detail\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ground_air_msgs::MissionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
      stream.next(m.current_index);
      stream.next(m.total_goals);
      stream.next(m.mission_id);
      stream.next(m.detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::MissionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::MissionStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.current_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_goals: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_goals);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mission_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mission_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_MISSIONSTATUS_H
