// Generated by gencpp from file ground_air_msgs/Relocalize.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_RELOCALIZE_H
#define GROUND_AIR_MSGS_MESSAGE_RELOCALIZE_H

#include <ros/service_traits.h>


#include <ground_air_msgs/RelocalizeRequest.h>
#include <ground_air_msgs/RelocalizeResponse.h>


namespace ground_air_msgs
{

struct Relocalize
{

typedef RelocalizeRequest Request;
typedef RelocalizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Relocalize
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::Relocalize > {
  static const char* value()
  {
    return "c61b338cbffb25ec319cc4dabf79db05";
  }

  static const char* value(const ::ground_air_msgs::Relocalize&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::Relocalize > {
  static const char* value()
  {
    return "ground_air_msgs/Relocalize";
  }

  static const char* value(const ::ground_air_msgs::Relocalize&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::RelocalizeRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::Relocalize >
template<>
struct MD5Sum< ::ground_air_msgs::RelocalizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::Relocalize >::value();
  }
  static const char* value(const ::ground_air_msgs::RelocalizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::RelocalizeRequest> should match
// service_traits::DataType< ::ground_air_msgs::Relocalize >
template<>
struct DataType< ::ground_air_msgs::RelocalizeRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::Relocalize >::value();
  }
  static const char* value(const ::ground_air_msgs::RelocalizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::RelocalizeResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::Relocalize >
template<>
struct MD5Sum< ::ground_air_msgs::RelocalizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::Relocalize >::value();
  }
  static const char* value(const ::ground_air_msgs::RelocalizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::RelocalizeResponse> should match
// service_traits::DataType< ::ground_air_msgs::Relocalize >
template<>
struct DataType< ::ground_air_msgs::RelocalizeResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::Relocalize >::value();
  }
  static const char* value(const ::ground_air_msgs::RelocalizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_RELOCALIZE_H
