// Generated by gencpp from file ground_air_msgs/RelocalizeRequest.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_RELOCALIZEREQUEST_H
#define GROUND_AIR_MSGS_MESSAGE_RELOCALIZEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovarianceStamped.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct RelocalizeRequest_
{
  typedef RelocalizeRequest_<ContainerAllocator> Type;

  RelocalizeRequest_()
    : use_initial_guess(false)
    , initial_guess()
    , timeout(0.0)  {
    }
  RelocalizeRequest_(const ContainerAllocator& _alloc)
    : use_initial_guess(false)
    , initial_guess(_alloc)
    , timeout(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _use_initial_guess_type;
  _use_initial_guess_type use_initial_guess;

   typedef  ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator>  _initial_guess_type;
  _initial_guess_type initial_guess;

   typedef double _timeout_type;
  _timeout_type timeout;





  typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelocalizeRequest_

typedef ::ground_air_msgs::RelocalizeRequest_<std::allocator<void> > RelocalizeRequest;

typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeRequest > RelocalizeRequestPtr;
typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeRequest const> RelocalizeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.use_initial_guess == rhs.use_initial_guess &&
    lhs.initial_guess == rhs.initial_guess &&
    lhs.timeout == rhs.timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38a86b8be42751f8c4670c5b973218e7";
  }

  static const char* value(const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38a86b8be42751f8ULL;
  static const uint64_t static_value2 = 0xc4670c5b973218e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/RelocalizeRequest";
  }

  static const char* value(const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool use_initial_guess\n"
"geometry_msgs/PoseWithCovarianceStamped initial_guess\n"
"float64 timeout\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovarianceStamped\n"
"# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.use_initial_guess);
      stream.next(m.initial_guess);
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelocalizeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::RelocalizeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "use_initial_guess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_initial_guess);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "initial_guess: ";
    Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.initial_guess);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timeout: ";
    Printer<double>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_RELOCALIZEREQUEST_H
