// Generated by gencpp from file ground_air_msgs/RelocalizeResponse.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_RELOCALIZERESPONSE_H
#define GROUND_AIR_MSGS_MESSAGE_RELOCALIZERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct RelocalizeResponse_
{
  typedef RelocalizeResponse_<ContainerAllocator> Type;

  RelocalizeResponse_()
    : success(false)
    , message()
    , pose()
    , fitness(0.0)
    , rmse(0.0)  {
    }
  RelocalizeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , pose(_alloc)
    , fitness(0.0)
    , rmse(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _fitness_type;
  _fitness_type fitness;

   typedef double _rmse_type;
  _rmse_type rmse;





  typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RelocalizeResponse_

typedef ::ground_air_msgs::RelocalizeResponse_<std::allocator<void> > RelocalizeResponse;

typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeResponse > RelocalizeResponsePtr;
typedef boost::shared_ptr< ::ground_air_msgs::RelocalizeResponse const> RelocalizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.pose == rhs.pose &&
    lhs.fitness == rhs.fitness &&
    lhs.rmse == rhs.rmse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "497124ea16f468a12b52f1f8f4476ae7";
  }

  static const char* value(const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x497124ea16f468a1ULL;
  static const uint64_t static_value2 = 0x2b52f1f8f4476ae7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/RelocalizeResponse";
  }

  static const char* value(const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"geometry_msgs/PoseStamped pose\n"
"float64 fitness\n"
"float64 rmse\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.pose);
      stream.next(m.fitness);
      stream.next(m.rmse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelocalizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::RelocalizeResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fitness: ";
    Printer<double>::stream(s, indent + "  ", v.fitness);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rmse: ";
    Printer<double>::stream(s, indent + "  ", v.rmse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_RELOCALIZERESPONSE_H
