// Generated by gencpp from file ground_air_msgs/SaveMappingResponse.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SAVEMAPPINGRESPONSE_H
#define GROUND_AIR_MSGS_MESSAGE_SAVEMAPPINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ground_air_msgs/MappingStatus.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SaveMappingResponse_
{
  typedef SaveMappingResponse_<ContainerAllocator> Type;

  SaveMappingResponse_()
    : success(false)
    , message()
    , map_directory()
    , point_count(0)
    , map_area(0.0)
    , status()  {
    }
  SaveMappingResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , map_directory(_alloc)
    , point_count(0)
    , map_area(0.0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_directory_type;
  _map_directory_type map_directory;

   typedef uint64_t _point_count_type;
  _point_count_type point_count;

   typedef double _map_area_type;
  _map_area_type map_area;

   typedef  ::ground_air_msgs::MappingStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMappingResponse_

typedef ::ground_air_msgs::SaveMappingResponse_<std::allocator<void> > SaveMappingResponse;

typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingResponse > SaveMappingResponsePtr;
typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingResponse const> SaveMappingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.map_directory == rhs.map_directory &&
    lhs.point_count == rhs.point_count &&
    lhs.map_area == rhs.map_area &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b55b1aad9049fd292f476b6b721de723";
  }

  static const char* value(const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb55b1aad9049fd29ULL;
  static const uint64_t static_value2 = 0x2f476b6b721de723ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SaveMappingResponse";
  }

  static const char* value(const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"string map_directory\n"
"uint64 point_count\n"
"float64 map_area\n"
"ground_air_msgs/MappingStatus status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ground_air_msgs/MappingStatus\n"
"std_msgs/Header header\n"
"\n"
"uint8 IDLE=0\n"
"uint8 RECORDING=1\n"
"uint8 SAVING=2\n"
"uint8 COMPLETE=3\n"
"uint8 ERROR=4\n"
"\n"
"uint8 state\n"
"string map_id\n"
"uint64 point_count\n"
"float64 map_area\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.map_directory);
      stream.next(m.point_count);
      stream.next(m.map_area);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMappingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::SaveMappingResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_directory: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_directory);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point_count: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.point_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_area: ";
    Printer<double>::stream(s, indent + "  ", v.map_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer< ::ground_air_msgs::MappingStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SAVEMAPPINGRESPONSE_H
