// Generated by gencpp from file ground_air_msgs/SaveMapping.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SAVEMAPPING_H
#define GROUND_AIR_MSGS_MESSAGE_SAVEMAPPING_H

#include <ros/service_traits.h>


#include <ground_air_msgs/SaveMappingRequest.h>
#include <ground_air_msgs/SaveMappingResponse.h>


namespace ground_air_msgs
{

struct SaveMapping
{

typedef SaveMappingRequest Request;
typedef SaveMappingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMapping
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::SaveMapping > {
  static const char* value()
  {
    return "b55b1aad9049fd292f476b6b721de723";
  }

  static const char* value(const ::ground_air_msgs::SaveMapping&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::SaveMapping > {
  static const char* value()
  {
    return "ground_air_msgs/SaveMapping";
  }

  static const char* value(const ::ground_air_msgs::SaveMapping&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::SaveMappingRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::SaveMapping >
template<>
struct MD5Sum< ::ground_air_msgs::SaveMappingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SaveMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::SaveMappingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SaveMappingRequest> should match
// service_traits::DataType< ::ground_air_msgs::SaveMapping >
template<>
struct DataType< ::ground_air_msgs::SaveMappingRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SaveMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::SaveMappingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::SaveMappingResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::SaveMapping >
template<>
struct MD5Sum< ::ground_air_msgs::SaveMappingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SaveMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::SaveMappingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SaveMappingResponse> should match
// service_traits::DataType< ::ground_air_msgs::SaveMapping >
template<>
struct DataType< ::ground_air_msgs::SaveMappingResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SaveMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::SaveMappingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SAVEMAPPING_H
