// Generated by gencpp from file ground_air_msgs/SaveMappingRequest.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SAVEMAPPINGREQUEST_H
#define GROUND_AIR_MSGS_MESSAGE_SAVEMAPPINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SaveMappingRequest_
{
  typedef SaveMappingRequest_<ContainerAllocator> Type;

  SaveMappingRequest_()
    {
    }
  SaveMappingRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMappingRequest_

typedef ::ground_air_msgs::SaveMappingRequest_<std::allocator<void> > SaveMappingRequest;

typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingRequest > SaveMappingRequestPtr;
typedef boost::shared_ptr< ::ground_air_msgs::SaveMappingRequest const> SaveMappingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SaveMappingRequest";
  }

  static const char* value(const ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMappingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ground_air_msgs::SaveMappingRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SAVEMAPPINGREQUEST_H
