// Generated by gencpp from file ground_air_msgs/SetEmergencyStopResponse.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOPRESPONSE_H
#define GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ground_air_msgs/VehicleStatus.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SetEmergencyStopResponse_
{
  typedef SetEmergencyStopResponse_<ContainerAllocator> Type;

  SetEmergencyStopResponse_()
    : success(false)
    , message()
    , status()  {
    }
  SetEmergencyStopResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef  ::ground_air_msgs::VehicleStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetEmergencyStopResponse_

typedef ::ground_air_msgs::SetEmergencyStopResponse_<std::allocator<void> > SetEmergencyStopResponse;

typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopResponse > SetEmergencyStopResponsePtr;
typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopResponse const> SetEmergencyStopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0928d6f1b6cc7f23580e750a31f1e15";
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0928d6f1b6cc7f2ULL;
  static const uint64_t static_value2 = 0x3580e750a31f1e15ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SetEmergencyStopResponse";
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"ground_air_msgs/VehicleStatus status\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ground_air_msgs/VehicleStatus\n"
"std_msgs/Header header\n"
"\n"
"uint8 UNKNOWN=0\n"
"uint8 GROUND=1\n"
"uint8 TAKEOFF=2\n"
"uint8 AIR=3\n"
"uint8 LANDING=4\n"
"uint8 ESTOP=5\n"
"uint8 FAULT=6\n"
"\n"
"uint8 mode\n"
"bool connected\n"
"bool armed\n"
"bool localized\n"
"bool emergency_stop\n"
"float32 altitude\n"
"string flight_mode\n"
"string detail\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEmergencyStopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::SetEmergencyStopResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOPRESPONSE_H
