// Generated by gencpp from file ground_air_msgs/SetEmergencyStopRequest.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOPREQUEST_H
#define GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SetEmergencyStopRequest_
{
  typedef SetEmergencyStopRequest_<ContainerAllocator> Type;

  SetEmergencyStopRequest_()
    : active(false)  {
    }
  SetEmergencyStopRequest_(const ContainerAllocator& _alloc)
    : active(false)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEmergencyStopRequest_

typedef ::ground_air_msgs::SetEmergencyStopRequest_<std::allocator<void> > SetEmergencyStopRequest;

typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopRequest > SetEmergencyStopRequestPtr;
typedef boost::shared_ptr< ::ground_air_msgs::SetEmergencyStopRequest const> SetEmergencyStopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator2> & rhs)
{
  return lhs.active == rhs.active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c5cfb0a2565df41de6873994aee57d2";
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c5cfb0a2565df41ULL;
  static const uint64_t static_value2 = 0xde6873994aee57d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SetEmergencyStopRequest";
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool active\n"
;
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEmergencyStopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::SetEmergencyStopRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOPREQUEST_H
