// Generated by gencpp from file ground_air_msgs/SetEmergencyStop.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOP_H
#define GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOP_H

#include <ros/service_traits.h>


#include <ground_air_msgs/SetEmergencyStopRequest.h>
#include <ground_air_msgs/SetEmergencyStopResponse.h>


namespace ground_air_msgs
{

struct SetEmergencyStop
{

typedef SetEmergencyStopRequest Request;
typedef SetEmergencyStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEmergencyStop
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::SetEmergencyStop > {
  static const char* value()
  {
    return "6adfca563192fe56ca02041330bd55c8";
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStop&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::SetEmergencyStop > {
  static const char* value()
  {
    return "ground_air_msgs/SetEmergencyStop";
  }

  static const char* value(const ::ground_air_msgs::SetEmergencyStop&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::SetEmergencyStopRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::SetEmergencyStop >
template<>
struct MD5Sum< ::ground_air_msgs::SetEmergencyStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SetEmergencyStop >::value();
  }
  static const char* value(const ::ground_air_msgs::SetEmergencyStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SetEmergencyStopRequest> should match
// service_traits::DataType< ::ground_air_msgs::SetEmergencyStop >
template<>
struct DataType< ::ground_air_msgs::SetEmergencyStopRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SetEmergencyStop >::value();
  }
  static const char* value(const ::ground_air_msgs::SetEmergencyStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::SetEmergencyStopResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::SetEmergencyStop >
template<>
struct MD5Sum< ::ground_air_msgs::SetEmergencyStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SetEmergencyStop >::value();
  }
  static const char* value(const ::ground_air_msgs::SetEmergencyStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SetEmergencyStopResponse> should match
// service_traits::DataType< ::ground_air_msgs::SetEmergencyStop >
template<>
struct DataType< ::ground_air_msgs::SetEmergencyStopResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SetEmergencyStop >::value();
  }
  static const char* value(const ::ground_air_msgs::SetEmergencyStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SETEMERGENCYSTOP_H
