// Generated by gencpp from file ground_air_msgs/SetVehicleModeRequest.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SETVEHICLEMODEREQUEST_H
#define GROUND_AIR_MSGS_MESSAGE_SETVEHICLEMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SetVehicleModeRequest_
{
  typedef SetVehicleModeRequest_<ContainerAllocator> Type;

  SetVehicleModeRequest_()
    : target_mode(0)  {
    }
  SetVehicleModeRequest_(const ContainerAllocator& _alloc)
    : target_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _target_mode_type;
  _target_mode_type target_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GROUND)
  #undef GROUND
#endif
#if defined(_WIN32) && defined(AIR)
  #undef AIR
#endif

  enum {
    GROUND = 1u,
    AIR = 3u,
  };


  typedef boost::shared_ptr< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetVehicleModeRequest_

typedef ::ground_air_msgs::SetVehicleModeRequest_<std::allocator<void> > SetVehicleModeRequest;

typedef boost::shared_ptr< ::ground_air_msgs::SetVehicleModeRequest > SetVehicleModeRequestPtr;
typedef boost::shared_ptr< ::ground_air_msgs::SetVehicleModeRequest const> SetVehicleModeRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_mode == rhs.target_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2278b60c8ae8a1e23e584b07983ecfd3";
  }

  static const char* value(const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2278b60c8ae8a1e2ULL;
  static const uint64_t static_value2 = 0x3e584b07983ecfd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SetVehicleModeRequest";
  }

  static const char* value(const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 GROUND=1\n"
"uint8 AIR=3\n"
"uint8 target_mode\n"
;
  }

  static const char* value(const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVehicleModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::SetVehicleModeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.target_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SETVEHICLEMODEREQUEST_H
