// Generated by gencpp from file ground_air_msgs/SetVehicleMode.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SETVEHICLEMODE_H
#define GROUND_AIR_MSGS_MESSAGE_SETVEHICLEMODE_H

#include <ros/service_traits.h>


#include <ground_air_msgs/SetVehicleModeRequest.h>
#include <ground_air_msgs/SetVehicleModeResponse.h>


namespace ground_air_msgs
{

struct SetVehicleMode
{

typedef SetVehicleModeRequest Request;
typedef SetVehicleModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVehicleMode
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::SetVehicleMode > {
  static const char* value()
  {
    return "ec2c78fe35d8769d286703fa442499f8";
  }

  static const char* value(const ::ground_air_msgs::SetVehicleMode&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::SetVehicleMode > {
  static const char* value()
  {
    return "ground_air_msgs/SetVehicleMode";
  }

  static const char* value(const ::ground_air_msgs::SetVehicleMode&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::SetVehicleModeRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::SetVehicleMode >
template<>
struct MD5Sum< ::ground_air_msgs::SetVehicleModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SetVehicleMode >::value();
  }
  static const char* value(const ::ground_air_msgs::SetVehicleModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SetVehicleModeRequest> should match
// service_traits::DataType< ::ground_air_msgs::SetVehicleMode >
template<>
struct DataType< ::ground_air_msgs::SetVehicleModeRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SetVehicleMode >::value();
  }
  static const char* value(const ::ground_air_msgs::SetVehicleModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::SetVehicleModeResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::SetVehicleMode >
template<>
struct MD5Sum< ::ground_air_msgs::SetVehicleModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SetVehicleMode >::value();
  }
  static const char* value(const ::ground_air_msgs::SetVehicleModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SetVehicleModeResponse> should match
// service_traits::DataType< ::ground_air_msgs::SetVehicleMode >
template<>
struct DataType< ::ground_air_msgs::SetVehicleModeResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SetVehicleMode >::value();
  }
  static const char* value(const ::ground_air_msgs::SetVehicleModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SETVEHICLEMODE_H
