// Generated by gencpp from file ground_air_msgs/StartMapping.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_STARTMAPPING_H
#define GROUND_AIR_MSGS_MESSAGE_STARTMAPPING_H

#include <ros/service_traits.h>


#include <ground_air_msgs/StartMappingRequest.h>
#include <ground_air_msgs/StartMappingResponse.h>


namespace ground_air_msgs
{

struct StartMapping
{

typedef StartMappingRequest Request;
typedef StartMappingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartMapping
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::StartMapping > {
  static const char* value()
  {
    return "7109d91bb5e43bd6cea8265829bbdff6";
  }

  static const char* value(const ::ground_air_msgs::StartMapping&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::StartMapping > {
  static const char* value()
  {
    return "ground_air_msgs/StartMapping";
  }

  static const char* value(const ::ground_air_msgs::StartMapping&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::StartMappingRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::StartMapping >
template<>
struct MD5Sum< ::ground_air_msgs::StartMappingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::StartMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::StartMappingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::StartMappingRequest> should match
// service_traits::DataType< ::ground_air_msgs::StartMapping >
template<>
struct DataType< ::ground_air_msgs::StartMappingRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::StartMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::StartMappingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::StartMappingResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::StartMapping >
template<>
struct MD5Sum< ::ground_air_msgs::StartMappingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::StartMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::StartMappingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::StartMappingResponse> should match
// service_traits::DataType< ::ground_air_msgs::StartMapping >
template<>
struct DataType< ::ground_air_msgs::StartMappingResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::StartMapping >::value();
  }
  static const char* value(const ::ground_air_msgs::StartMappingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_STARTMAPPING_H
