// Generated by gencpp from file ground_air_msgs/SubmitMissionResponse.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SUBMITMISSIONRESPONSE_H
#define GROUND_AIR_MSGS_MESSAGE_SUBMITMISSIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SubmitMissionResponse_
{
  typedef SubmitMissionResponse_<ContainerAllocator> Type;

  SubmitMissionResponse_()
    : accepted(false)
    , message()
    , goal_count(0)  {
    }
  SubmitMissionResponse_(const ContainerAllocator& _alloc)
    : accepted(false)
    , message(_alloc)
    , goal_count(0)  {
  (void)_alloc;
    }



   typedef uint8_t _accepted_type;
  _accepted_type accepted;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint32_t _goal_count_type;
  _goal_count_type goal_count;





  typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SubmitMissionResponse_

typedef ::ground_air_msgs::SubmitMissionResponse_<std::allocator<void> > SubmitMissionResponse;

typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionResponse > SubmitMissionResponsePtr;
typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionResponse const> SubmitMissionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.accepted == rhs.accepted &&
    lhs.message == rhs.message &&
    lhs.goal_count == rhs.goal_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a8874339fceff65d93337f129e3c7b6";
  }

  static const char* value(const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a8874339fceff65ULL;
  static const uint64_t static_value2 = 0xd93337f129e3c7b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SubmitMissionResponse";
  }

  static const char* value(const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool accepted\n"
"string message\n"
"uint32 goal_count\n"
"\n"
;
  }

  static const char* value(const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
      stream.next(m.message);
      stream.next(m.goal_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubmitMissionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::SubmitMissionResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accepted);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.goal_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SUBMITMISSIONRESPONSE_H
