// Generated by gencpp from file ground_air_msgs/SubmitMission.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SUBMITMISSION_H
#define GROUND_AIR_MSGS_MESSAGE_SUBMITMISSION_H

#include <ros/service_traits.h>


#include <ground_air_msgs/SubmitMissionRequest.h>
#include <ground_air_msgs/SubmitMissionResponse.h>


namespace ground_air_msgs
{

struct SubmitMission
{

typedef SubmitMissionRequest Request;
typedef SubmitMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubmitMission
} // namespace ground_air_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_air_msgs::SubmitMission > {
  static const char* value()
  {
    return "0b7be7b794768c0b19086f237b7f7bf0";
  }

  static const char* value(const ::ground_air_msgs::SubmitMission&) { return value(); }
};

template<>
struct DataType< ::ground_air_msgs::SubmitMission > {
  static const char* value()
  {
    return "ground_air_msgs/SubmitMission";
  }

  static const char* value(const ::ground_air_msgs::SubmitMission&) { return value(); }
};


// service_traits::MD5Sum< ::ground_air_msgs::SubmitMissionRequest> should match
// service_traits::MD5Sum< ::ground_air_msgs::SubmitMission >
template<>
struct MD5Sum< ::ground_air_msgs::SubmitMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SubmitMission >::value();
  }
  static const char* value(const ::ground_air_msgs::SubmitMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SubmitMissionRequest> should match
// service_traits::DataType< ::ground_air_msgs::SubmitMission >
template<>
struct DataType< ::ground_air_msgs::SubmitMissionRequest>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SubmitMission >::value();
  }
  static const char* value(const ::ground_air_msgs::SubmitMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_air_msgs::SubmitMissionResponse> should match
// service_traits::MD5Sum< ::ground_air_msgs::SubmitMission >
template<>
struct MD5Sum< ::ground_air_msgs::SubmitMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_air_msgs::SubmitMission >::value();
  }
  static const char* value(const ::ground_air_msgs::SubmitMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_air_msgs::SubmitMissionResponse> should match
// service_traits::DataType< ::ground_air_msgs::SubmitMission >
template<>
struct DataType< ::ground_air_msgs::SubmitMissionResponse>
{
  static const char* value()
  {
    return DataType< ::ground_air_msgs::SubmitMission >::value();
  }
  static const char* value(const ::ground_air_msgs::SubmitMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SUBMITMISSION_H
