// Generated by gencpp from file ground_air_msgs/SubmitMissionRequest.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_SUBMITMISSIONREQUEST_H
#define GROUND_AIR_MSGS_MESSAGE_SUBMITMISSIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct SubmitMissionRequest_
{
  typedef SubmitMissionRequest_<ContainerAllocator> Type;

  SubmitMissionRequest_()
    : mission_id()
    , goals()  {
    }
  SubmitMissionRequest_(const ContainerAllocator& _alloc)
    : mission_id(_alloc)
    , goals(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mission_id_type;
  _mission_id_type mission_id;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _goals_type;
  _goals_type goals;





  typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SubmitMissionRequest_

typedef ::ground_air_msgs::SubmitMissionRequest_<std::allocator<void> > SubmitMissionRequest;

typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionRequest > SubmitMissionRequestPtr;
typedef boost::shared_ptr< ::ground_air_msgs::SubmitMissionRequest const> SubmitMissionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mission_id == rhs.mission_id &&
    lhs.goals == rhs.goals;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator1> & lhs, const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e691f5914610d0d03746740d82f81b59";
  }

  static const char* value(const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe691f5914610d0d0ULL;
  static const uint64_t static_value2 = 0x3746740d82f81b59ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/SubmitMissionRequest";
  }

  static const char* value(const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mission_id\n"
"geometry_msgs/PoseStamped[] goals\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_id);
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubmitMissionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::SubmitMissionRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mission_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mission_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goals: ";
    if (v.goals.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.goals.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.goals[i]);
    }
    if (v.goals.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_SUBMITMISSIONREQUEST_H
