// Generated by gencpp from file ground_air_msgs/VehicleStatus.msg
// DO NOT EDIT!


#ifndef GROUND_AIR_MSGS_MESSAGE_VEHICLESTATUS_H
#define GROUND_AIR_MSGS_MESSAGE_VEHICLESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ground_air_msgs
{
template <class ContainerAllocator>
struct VehicleStatus_
{
  typedef VehicleStatus_<ContainerAllocator> Type;

  VehicleStatus_()
    : header()
    , mode(0)
    , connected(false)
    , armed(false)
    , localized(false)
    , emergency_stop(false)
    , altitude(0.0)
    , flight_mode()
    , detail()  {
    }
  VehicleStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , connected(false)
    , armed(false)
    , localized(false)
    , emergency_stop(false)
    , altitude(0.0)
    , flight_mode(_alloc)
    , detail(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _connected_type;
  _connected_type connected;

   typedef uint8_t _armed_type;
  _armed_type armed;

   typedef uint8_t _localized_type;
  _localized_type localized;

   typedef uint8_t _emergency_stop_type;
  _emergency_stop_type emergency_stop;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _flight_mode_type;
  _flight_mode_type flight_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _detail_type;
  _detail_type detail;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(UNKNOWN)
  #undef UNKNOWN
#endif
#if defined(_WIN32) && defined(GROUND)
  #undef GROUND
#endif
#if defined(_WIN32) && defined(TAKEOFF)
  #undef TAKEOFF
#endif
#if defined(_WIN32) && defined(AIR)
  #undef AIR
#endif
#if defined(_WIN32) && defined(LANDING)
  #undef LANDING
#endif
#if defined(_WIN32) && defined(ESTOP)
  #undef ESTOP
#endif
#if defined(_WIN32) && defined(FAULT)
  #undef FAULT
#endif

  enum {
    UNKNOWN = 0u,
    GROUND = 1u,
    TAKEOFF = 2u,
    AIR = 3u,
    LANDING = 4u,
    ESTOP = 5u,
    FAULT = 6u,
  };


  typedef boost::shared_ptr< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleStatus_

typedef ::ground_air_msgs::VehicleStatus_<std::allocator<void> > VehicleStatus;

typedef boost::shared_ptr< ::ground_air_msgs::VehicleStatus > VehicleStatusPtr;
typedef boost::shared_ptr< ::ground_air_msgs::VehicleStatus const> VehicleStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_air_msgs::VehicleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_air_msgs::VehicleStatus_<ContainerAllocator1> & lhs, const ::ground_air_msgs::VehicleStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode &&
    lhs.connected == rhs.connected &&
    lhs.armed == rhs.armed &&
    lhs.localized == rhs.localized &&
    lhs.emergency_stop == rhs.emergency_stop &&
    lhs.altitude == rhs.altitude &&
    lhs.flight_mode == rhs.flight_mode &&
    lhs.detail == rhs.detail;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_air_msgs::VehicleStatus_<ContainerAllocator1> & lhs, const ::ground_air_msgs::VehicleStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_air_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95fa82c3b8b77ebda59f5cb1adfd1b65";
  }

  static const char* value(const ::ground_air_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95fa82c3b8b77ebdULL;
  static const uint64_t static_value2 = 0xa59f5cb1adfd1b65ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_air_msgs/VehicleStatus";
  }

  static const char* value(const ::ground_air_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"uint8 UNKNOWN=0\n"
"uint8 GROUND=1\n"
"uint8 TAKEOFF=2\n"
"uint8 AIR=3\n"
"uint8 LANDING=4\n"
"uint8 ESTOP=5\n"
"uint8 FAULT=6\n"
"\n"
"uint8 mode\n"
"bool connected\n"
"bool armed\n"
"bool localized\n"
"bool emergency_stop\n"
"float32 altitude\n"
"string flight_mode\n"
"string detail\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ground_air_msgs::VehicleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.connected);
      stream.next(m.armed);
      stream.next(m.localized);
      stream.next(m.emergency_stop);
      stream.next(m.altitude);
      stream.next(m.flight_mode);
      stream.next(m.detail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_air_msgs::VehicleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_air_msgs::VehicleStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "armed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "localized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.localized);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "emergency_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_stop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flight_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.flight_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_AIR_MSGS_MESSAGE_VEHICLESTATUS_H
